name: Build Forge Mod

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Lấy source code từ repo
    - name: Checkout repository
      uses: actions/checkout@v4

    # Cài JDK 17 (Forge 1.21.1 cần Java 17)
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # Cache Gradle để build nhanh hơn
    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # Fix lỗi Permission denied cho gradlew
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Build mod bằng Gradle
    - name: Build with Gradle
      run: ./gradlew build --no-daemon

    # Upload file JAR build ra để tải về
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: forge-mod-build
        path: build/libs/*.jar
